version: "3"

services:
  webserver:
    build:
      context: ./.docker/bin/webserver
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ${DOCUMENT_ROOT-./}:/var/www/html
      - ${PHP_INI-./.docker/config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./.docker/config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./.docker/logs/apache2}:/var/log/apache2
  db:
    image: postgres:12.4
    restart: always
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
        - 5432:5432
    volumes:
        - ./.docker/config/postgres/:/docker-entrypoint-initdb.d/

